M48
; DRILL file {KiCad (6.0.6)} date Sun Jun 26 20:01:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-26T20:01:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1570
%
G90
G05
T1
X3.3Y-3.5
X3.7Y-3.5
X4.05Y-3.5
X4.45Y-3.5
X4.8Y-3.5
X5.2Y-3.5
X5.55Y-3.5
X5.95Y-3.5
T2
X3.5Y-3.5
X4.25Y-3.5
X5.0Y-3.5
X5.75Y-3.5
T0
M30
